name: "My First GitHub Actions"

on: push

jobs:
  first_job:
    name: "First Job"
    runs-on: ubuntu-latest

    steps:
      - name: Mask output value
        id: first
        shell: bash
        run: |
          value1='This is the first value'


          echo "::add-mask::$value1"
          echo "::set-output name=first_value::$value1"

      - name: Check output value
        shell: bash
        run: |
          value1='This is the first value'

          echo "value: ${{ steps.first.outputs.first_value }}"

      - name: Check github secrets
        shell: bash
        run: |
          echo "secret: ${{ secrets.HELLO }}"
